// The ONLY place the offer tiles talk to the backend. Contract:
// docs/sera-interview-contract.md
//
// Offers are generated by the LLM when the résumé is read (so the tiles appear
// instantly after screening), always with INVENTED company names — never real
// companies — and different for every CV.
import { isMockMode } from './seraAuthService'

// DEV ONLY mock. The check is written inline (import.meta.env.DEV && ...) so
// the bundler can drop the sample offers from production builds.
const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms))

const MOCK_OFFERS = [
  {
    id: 'offer-kavira',
    company: 'Kavira Data Labs',
    logoLetter: 'K',
    city: 'Pune',
    workMode: 'Hybrid',
    role: 'Junior Data Analyst',
    ctcMinLpa: 4,
    ctcMaxLpa: 6,
    skills: ['SQL', 'Excel', 'Power BI'],
    whyFit: 'Your reporting work maps straight onto their weekly sales dashboards.',
  },
  {
    id: 'offer-tidewell',
    company: 'Tidewell Retail Technologies',
    logoLetter: 'T',
    city: 'Bengaluru',
    workMode: 'On-site',
    role: 'Business Analyst',
    ctcMinLpa: 5,
    ctcMaxLpa: 7.5,
    skills: ['Stakeholder updates', 'Excel', 'Process mapping'],
    whyFit: 'You explained trade-offs clearly — that is most of this role.',
  },
  {
    id: 'offer-brightlane',
    company: 'Brightlane Fintech',
    logoLetter: 'B',
    city: 'Mumbai',
    workMode: 'Remote',
    role: 'Reporting Analyst',
    ctcMinLpa: 4.5,
    ctcMaxLpa: 6.5,
    skills: ['Python basics', 'SQL', 'Data cleaning'],
    whyFit: 'Your data-cleaning project is exactly the daily work here.',
  },
]

async function postJson(path, body) {
  try {
    const res = await fetch(path, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    })
    if (!res.headers.get('content-type')?.includes('application/json')) return null
    return await res.json()
  } catch {
    return null
  }
}

// → { offers: [{ id, company, logoLetter, city, workMode, role, ctcMinLpa, ctcMaxLpa, skills: [3], whyFit }] ×3 }
//   | { offers: null, error }
export async function getOffers(sessionId) {
  if (import.meta.env.DEV && isMockMode()) {
    await wait(300)
    return { offers: MOCK_OFFERS }
  }
  // TODO(backend): POST /api/sera/offers — not built yet.
  const data = await postJson('/api/sera/offers', { sessionId })
  if (!Array.isArray(data?.offers)) return { offers: null, error: "We couldn't load your offers. Please try again." }
  return data
}

// → { ok: true } | { ok: false, error }
export async function saveOfferChoice(sessionId, offerId) {
  if (import.meta.env.DEV && isMockMode()) {
    await wait(150)
    return { ok: true }
  }
  // TODO(backend): POST /api/sera/offers/choose — not built yet.
  const data = await postJson('/api/sera/offers/choose', { sessionId, offerId })
  if (typeof data?.ok !== 'boolean') return { ok: false, error: "We couldn't save your choice. Please try again." }
  return data
}
